export const PRODUCTS = [
  // GROCERIES (EXOTIC)
  {
    id: 'p_truffle', name: 'Italian White Truffle (Alba)', brand: 'Tartufi Morra',
    category: 'Groceries (Exotic)', subcategory: 'Fresh Produce',
    country: 'Italy', flag: '🇮🇹',
    price: 12500, mrp: 15000, discount: 16, rating: 4.9, reviewCount: 42,
    image: 'https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=400&h=300&fit=crop&auto=format',
    description: 'Freshly harvested white winter truffles directly from the forests of Alba, Piedmont. Characterized by an intense, gas-like, garlic-honey aroma. Shaved raw over fine risottos or scrambled eggs, they melt into absolute gourmet perfection.',
    ingredients: '100% Organically foraged White Truffles (Tuber magnatum pico)',
    factsOrUsage: 'Serving size: 5g | Shelf life: 7 days | Maintain between 2–4°C wrapped in paper towel.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_mango', name: 'Japanese Miyazaki Mango', brand: 'Taiyo no Tamago',
    category: 'Groceries (Exotic)', subcategory: 'Fresh Fruit',
    country: 'Japan', flag: '🇯🇵',
    price: 4500, mrp: 5000, discount: 10, rating: 4.8, reviewCount: 19,
    image: 'https://images.unsplash.com/photo-1601493700631-2d16fa3b8d9f?w=400&h=300&fit=crop&auto=format',
    description: 'The high-end egg of the sun representing Japanese agricultural supremacy. Tree-ripened to guarantee a sugar content of 15% or above. The texture is completely fibreless, melting in your mouth like silk peach cream.',
    ingredients: '100% Tree-ripened export grade Miyazaki mango',
    factsOrUsage: 'Calories: 60 per 100g | Rich in Vitamin A & C | Premium presentation wooden box included. Serve chilled.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_saffron', name: 'Kashmiri Mongra Saffron', brand: 'Zaran Saffron',
    category: 'Groceries (Exotic)', subcategory: 'Spices & Herbs',
    country: 'India', flag: '🇮🇳',
    price: 850, mrp: 1000, discount: 15, rating: 4.7, reviewCount: 85,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop&auto=format',
    description: 'The rarest grade of Kashmiri saffron — Mongra — hand-picked at dawn during a 3-week annual harvest window. Deep crimson threads with an intense floral-honey aroma and a beautiful golden colour payoff.',
    ingredients: 'Pure Crocus sativus Mongra grade saffron threads',
    factsOrUsage: '0.1g per cup of warm milk | Store in airtight glass jar away from light | Use within 12 months.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_honey', name: 'Royal Yemeni Sidr Honey', brand: 'Balqees Honey',
    category: 'Groceries (Exotic)', subcategory: 'Pantry Essentials',
    country: 'Yemen', flag: '🇾🇪',
    price: 4200, mrp: 5000, discount: 16, rating: 4.9, reviewCount: 37,
    image: 'https://images.unsplash.com/photo-1587049633312-d628ae50a8ae?w=400&h=300&fit=crop&auto=format',
    description: 'Sourced from ancient Sidr trees in the Hadramaut Valley. Dense, caramel-like texture with notes of dried fruit and warm spice. Used medicinally in Arab royalty for centuries. Certified raw & unprocessed.',
    ingredients: '100% Raw unfiltered Sidr honey (Ziziphus spina-christi)',
    factsOrUsage: 'Calories: 64 per 15ml | Contains natural enzymes & antioxidants | Do not feed to infants under 12 months.',
    isDietVegan: false, isDietOrganic: true, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  // SNACKS
  {
    id: 'p_gold_chocolate', name: '24K Gold Dark Chocolate Truffles', brand: "Maison d'Or",
    category: 'Snacks', subcategory: 'Chocolates',
    country: 'France', flag: '🇫🇷',
    price: 3200, mrp: 4000, discount: 20, rating: 4.9, reviewCount: 56,
    image: 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=400&h=300&fit=crop&auto=format',
    description: 'Hand-rolled 72% dark chocolate truffles finished with edible 24-karat gold leaf. Ganache filled with aged cognac and Fleur de Sel. Presented in a black lacquered gift box. The ultimate indulgence.',
    ingredients: '72% Dark Chocolate (Criollo), Fresh Cream, Cognac, Fleur de Sel, 24K Edible Gold Leaf',
    factsOrUsage: 'Box of 6 | Calories: 90 per piece | Store below 18°C | Best consumed within 10 days.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: false, colorHex: null,
  },
  {
    id: 'p_caviar_chips', name: 'Caviar Potato Crisps', brand: 'Torres',
    category: 'Snacks', subcategory: 'Chips & Savory',
    country: 'Spain', flag: '🇪🇸',
    price: 490, mrp: 600, discount: 18, rating: 4.6, reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=300&fit=crop&auto=format',
    description: "Spain's most decorated premium crisp brand. Kettle-cooked with seasoning crafted from real Osetra caviar extract and Maldon sea salt. A surprisingly refined snacking experience.",
    ingredients: 'Potatoes, Olive Oil, Osetra Caviar Extract, Maldon Sea Salt, Natural Flavourings',
    factsOrUsage: 'Net weight: 110g | Best served alongside sparkling wine.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_matcha_pocky', name: 'Ceremonial Matcha Pocky Box', brand: 'Glico Premium',
    category: 'Snacks', subcategory: 'Sweets & Biscuits',
    country: 'Japan', flag: '🇯🇵',
    price: 620, mrp: 750, discount: 17, rating: 4.7, reviewCount: 94,
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=300&fit=crop&auto=format',
    description: "Limited reserve edition of Japan's most beloved biscuit stick. Made with first-flush ceremonial grade Uji matcha, providing an intensely green, slightly bitter, umami-forward coating.",
    ingredients: 'Wheat Flour, White Chocolate, Uji Matcha (ceremonial grade), Sugar, Butter',
    factsOrUsage: 'Box of 3 individual stick packs | Keep away from direct sunlight.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: false, colorHex: null,
  },
  // READY-TO-EAT
  {
    id: 'p_lobster_roll', name: 'Atlantic Lobster Roll Deluxe Kit', brand: 'Nova Scotia Blue',
    category: 'Ready-to-Eat', subcategory: 'Gourmet Meals',
    country: 'Canada', flag: '🇨🇦',
    price: 1850, mrp: 2200, discount: 15, rating: 4.8, reviewCount: 29,
    image: 'https://images.unsplash.com/photo-1559847260-76ea1574b4a6?w=400&h=300&fit=crop&auto=format',
    description: 'Chilled Atlantic lobster claw and knuckle meat, already poached and seasoned with tarragon butter. Arrives with a toasted brioche split roll. Just warm, assemble, and serve.',
    ingredients: 'Atlantic Lobster Meat, Cultured Butter, Tarragon, Sea Salt, Brioche Roll',
    factsOrUsage: 'Serves 2 | Calories: 380 per serving | Ready in under 8 minutes.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: false, colorHex: null,
  },
  {
    id: 'p_wagyu_sliders', name: 'A5 Kobe Wagyu Slidettes (2-Pack)', brand: 'Kobe Farms',
    category: 'Ready-to-Eat', subcategory: 'Gourmet Meals',
    country: 'Japan', flag: '🇯🇵',
    price: 2900, mrp: 3500, discount: 17, rating: 4.9, reviewCount: 51,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop&auto=format',
    description: 'BMS-12 rated A5 Kobe Wagyu beef patties, pre-seasoned with yuzu kosho and Himalayan salt. Pan-sear exactly 90 seconds each side for perfection. Comes with artisanal brioche buns and wasabi aioli.',
    ingredients: 'A5 Wagyu Beef (BMS12), Yuzu Kosho, Himalayan Salt, Brioche Bun, Wasabi Aioli',
    factsOrUsage: 'Pack of 2 sliders | Calories: 520 per slider | Keep refrigerated, consume within 48 hours.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: false, colorHex: null,
  },
  {
    id: 'p_mac_truffle', name: 'Gruyère & Black Truffle Gnocchi', brand: 'Maison Lux Bistro',
    category: 'Ready-to-Eat', subcategory: 'Gourmet Meals',
    country: 'Italy', flag: '🇮🇹',
    price: 1100, mrp: 1300, discount: 15, rating: 4.7, reviewCount: 44,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop&auto=format',
    description: 'Pillowy house-made potato gnocchi tossed in an aged Gruyère fondue laced with black Périgord truffle oil. Flash-frozen at source. Microwave-to-table in 4 minutes.',
    ingredients: 'Potato, Gruyère AOP Cheese, Périgord Black Truffle Oil, Cream, Butter, Chives',
    factsOrUsage: 'Serves 1 | Calories: 620 kcal | Microwave 3–4 minutes on high.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: false, colorHex: null,
  },
  // MAKEUP
  {
    id: 'p_lipstick_gold', name: 'Satin Champagne Gold Lipstick', brand: 'Aura Paris',
    category: 'Makeup', subcategory: 'Lips',
    country: 'France', flag: '🇫🇷',
    price: 4800, mrp: 5500, discount: 12, rating: 4.8, reviewCount: 31,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=300&fit=crop&auto=format',
    description: "A metallic pearlescent nude-gold lipstick with a silky satin finish. Infused with Argan oil and Vitamin E for 10-hour moisture wear. Perfect for Bangalore's gala soirées.",
    ingredients: 'Castor Oil, Argan Oil, Vitamin E, Mica (Gold Pigment), Silica, Candelilla Wax',
    factsOrUsage: 'Shade: #D4AF37 Champagne Gold | Apply with included lip liner for longevity | Cruelty-free.',
    isDietVegan: true, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: '#D4AF37',
  },
  {
    id: 'p_lipstick_crimson', name: 'Rose Velvet Matte Lipstick', brand: 'Aura Paris',
    category: 'Makeup', subcategory: 'Lips',
    country: 'France', flag: '🇫🇷',
    price: 4800, mrp: 5500, discount: 12, rating: 4.9, reviewCount: 68,
    image: 'https://images.unsplash.com/photo-1512496522148-0d546512eabc?w=400&h=300&fit=crop&auto=format',
    description: 'Intense deep crimson velvet matte. Transfer-resistant formula that delivers bold, unapologetic colour with zero feathering. A single swipe lasts 12 hours.',
    ingredients: 'Castor Oil, Jojoba Ester, Vitamin E, CI 15850 (Red 7), Silica, Candelilla Wax',
    factsOrUsage: 'Shade: #9C1C24 Deep Crimson | Full 12-hour wear | Cruelty-free, Fragrance-free.',
    isDietVegan: true, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: '#9C1C24',
  },
  {
    id: 'p_foundation_silk', name: 'Orchid Petal Serum Foundation', brand: 'Lumiere London',
    category: 'Makeup', subcategory: 'Face',
    country: 'United Kingdom', flag: '🇬🇧',
    price: 6100, mrp: 7000, discount: 12, rating: 4.7, reviewCount: 57,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=300&fit=crop&auto=format',
    description: 'A breathable serum-foundation hybrid that melts into skin like water. Infused with pink orchid stem cell extract for active treatment while delivering natural, skin-like radiance. SPF 30.',
    ingredients: 'Pink Orchid Stem Cells, Hyaluronic Acid, Niacinamide, Zinc Oxide SPF30, Squalane',
    factsOrUsage: 'Shade: Neutral Beige #F2C19E | Medium buildable coverage | Dermatologist-tested.',
    isDietVegan: true, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: '#F2C19E',
  },
  // SKINCARE
  {
    id: 'p_serum_orchid', name: 'Andean Black Orchid Renewal Essence', brand: 'Orchidée Royale',
    category: 'Skincare', subcategory: 'Serums & Elixirs',
    country: 'Monaco', flag: '🇲🇨',
    price: 18500, mrp: 22000, discount: 15, rating: 4.9, reviewCount: 26,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=300&fit=crop&auto=format',
    description: 'Monégasque luxury skin science at its zenith. Black orchid extract from the Andean highlands combined with 24K colloidal gold ions and retinol micro-spheres for overnight cellular regeneration.',
    ingredients: 'Black Orchid Extract, Colloidal Gold, Retinol Micro-Spheres, Hyaluronic Acid, Peptide Complex',
    factsOrUsage: '2 drops every night on clean skin. 30ml | Visible results in 14 days. Use SPF during the day.',
    isDietVegan: true, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_eye_cream', name: 'Beluga Caviar Overnight Eye Therapy', brand: 'Marine Lux',
    category: 'Skincare', subcategory: 'Eye Care',
    country: 'Switzerland', flag: '🇨🇭',
    price: 9400, mrp: 11000, discount: 14, rating: 4.8, reviewCount: 49,
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400&h=300&fit=crop&auto=format',
    description: 'Swiss biotech meets oceanic luxury. Beluga caviar extract delivers omega-3 fatty acids and amino acids directly to the delicate periorbital zone. Visibly reduces dark circles and puffiness by morning.',
    ingredients: 'Beluga Caviar Extract, Caffeine, Hyaluronic Acid, Ceramide NP, Niacinamide, Peptide-6',
    factsOrUsage: 'Dab gently with ring finger around orbital bone. 15ml. Use nightly for best results.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_saffron_oil', name: 'Kumkumadi & Kashmiri Saffron Glow Oil', brand: 'Ayur Lux',
    category: 'Skincare', subcategory: 'Face Oils',
    country: 'India', flag: '🇮🇳',
    price: 3100, mrp: 3800, discount: 18, rating: 4.9, reviewCount: 74,
    image: 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?w=400&h=300&fit=crop&auto=format',
    description: 'A 5,000-year Ayurvedic formulation reinterpreted with modern cold-press techniques. Kumkumadi oil blended with ultra-premium Kashmiri Mongra saffron threads. Reduces pigmentation and imparts a royal golden glow.',
    ingredients: 'Cold-pressed Sesame Oil, Kashmiri Mongra Saffron, Sandalwood, Lotus Petal Extract, Liquorice Root',
    factsOrUsage: '3 drops warmed between palms, press into damp skin at night. 30ml. For all skin types.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  // HAIR CARE
  {
    id: 'p_hair_elixir', name: 'South African Marula Glass Hair Elixir', brand: 'Satin Crown',
    category: 'Hair Care', subcategory: 'Hair Treatments',
    country: 'South Africa', flag: '🇿🇦',
    price: 4200, mrp: 5000, discount: 16, rating: 4.7, reviewCount: 63,
    image: 'https://images.unsplash.com/photo-1522338242292-6244253e7543?w=400&h=300&fit=crop&auto=format',
    description: 'Cold-pressed Marula oil from wild South African Sclerocarya birrea trees. An intensely lightweight, non-greasy oil that smooths frizz and imparts extraordinary mirror-like gloss to all hair types.',
    ingredients: 'Marula Oil (Sclerocarya birrea), Argan Oil, Camellia Seed Oil, Vitamin E, Silk Amino Acids',
    factsOrUsage: '2–3 drops on damp or dry hair. 50ml | Ideal for 2C–3A curl patterns. Heat protects up to 230°C.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_hair_mask', name: 'Caviar Bond Rehab Repair Mask', brand: 'Marine Lux',
    category: 'Hair Care', subcategory: 'Deep Conditioning',
    country: 'Switzerland', flag: '🇨🇭',
    price: 5800, mrp: 6800, discount: 14, rating: 4.8, reviewCount: 59,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=300&fit=crop&auto=format',
    description: 'Swiss marine science-formulated mask with Osetra caviar protein complex that molecularly bonds to damaged hair cortex strands. Delivers 3 weeks of frizz control in a single 15-minute application.',
    ingredients: 'Osetra Caviar Protein, Keratin Bond Complex, Hyaluronic Acid, Argan Oil, Silk Proteins',
    factsOrUsage: 'Apply to towel-dried hair. Leave 15 mins. Rinse. 200ml | For damaged, chemically-treated hair.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  // PREMIUM MEATS & SEAFOOD
  {
    id: 'p_wagyu_steak', name: 'A5 Kagoshima Wagyu Ribeye (200g)', brand: 'Japan Premium Beef',
    category: 'Meats & Seafood', subcategory: 'Premium Beef',
    country: 'Japan', flag: '🇯🇵',
    price: 8500, mrp: 10000, discount: 15, rating: 4.9, reviewCount: 38,
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=400&h=300&fit=crop&auto=format',
    description: 'A single perfectly marbled A5 Kagoshima Wagyu ribeye, wet-aged 28 days for maximum flavour development. BMS-10 rating. The intramuscular fat melts at body temperature, delivering an unparalleled butter-rich mouthfeel.',
    ingredients: '100% A5 Kagoshima Wagyu Beef, Himalayan Pink Salt (for curing)',
    factsOrUsage: 'Serves 1–2 | Pat dry, sear in cast iron 90 sec/side, rest 5 min | Store at 0–2°C, use within 48 hours.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_iberico', name: 'Jamón Ibérico de Bellota (100g)', brand: 'Cinco Jotas',
    category: 'Meats & Seafood', subcategory: 'Cured Charcuterie',
    country: 'Spain', flag: '🇪🇸',
    price: 3600, mrp: 4200, discount: 14, rating: 4.8, reviewCount: 44,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop&auto=format',
    description: 'Hand-sliced from 100% pure Iberian black-footed pigs, acorn-fed for 3 years in the Huelva dehesa. 36-month air-cured. The gold standard of Spanish charcuterie — deep ruby, nutty, intensely savoury.',
    ingredients: '100% Pure Iberian Pork Leg, Sea Salt',
    factsOrUsage: 'Serve at room temperature | Pairs with Manchego + dry Fino sherry | 100g hand-sliced.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_bluefin', name: 'Bluefin Otoro Sashimi Grade (150g)', brand: 'Tsukiji Select',
    category: 'Meats & Seafood', subcategory: 'Premium Seafood',
    country: 'Japan', flag: '🇯🇵',
    price: 6800, mrp: 8000, discount: 15, rating: 4.9, reviewCount: 27,
    image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&h=300&fit=crop&auto=format',
    description: 'The most prized cut of Pacific bluefin tuna — fatty otoro belly from the akami-side, sourced directly from Tsukiji-certified vessels. Flash-frozen at −60°C within hours of catch. Serve as sashimi with wasabi.',
    ingredients: 'Pacific Bluefin Tuna (Thunnus orientalis) - Otoro grade',
    factsOrUsage: 'Thaw in fridge 6 hours | Slice 5mm against grain | Serve with soy sauce and real wasabi.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_langoustine', name: 'Scottish Langoustine (500g Live)', brand: 'Loch Duart Reserve',
    category: 'Meats & Seafood', subcategory: 'Premium Seafood',
    country: 'United Kingdom', flag: '🇬🇧',
    price: 4900, mrp: 5800, discount: 15, rating: 4.7, reviewCount: 31,
    image: 'https://images.unsplash.com/photo-1559847260-76ea1574b4a6?w=400&h=300&fit=crop&auto=format',
    description: 'Live Scottish langoustines delivered in oxygenated water pouches. Caught in Scottish West Coast lochs, these are the sweetest crustaceans in the world — instantly superior to any frozen alternative.',
    ingredients: '100% Live Scottish Langoustine (Nephrops norvegicus)',
    factsOrUsage: 'Steam or boil 3–4 min | Serve with herb butter | Best consumed same day.',
    isDietVegan: false, isDietOrganic: true, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  // ARTISAN CHEESES
  {
    id: 'p_cheese_brie', name: 'Brie de Meaux AOP (250g)', brand: 'Fromagerie Dongé',
    category: 'Artisan Cheeses', subcategory: 'Soft Cheeses',
    country: 'France', flag: '🇫🇷',
    price: 1800, mrp: 2100, discount: 14, rating: 4.8, reviewCount: 52,
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=300&fit=crop&auto=format',
    description: 'The "King of Cheeses." Authentic AOP-certified Brie de Meaux from the Seine-et-Marne region. Creamy, mushroomy and lactic — with a paper-thin white Penicillium crust. At perfect ripeness.',
    ingredients: "Unpasteurised Cow's Milk, Salt, Penicillium candidum, Rennet",
    factsOrUsage: 'Serve at room temperature | Pairs with Champagne or light Pinot Noir | Consume within 5 days.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_cheese_parm', name: 'Parmigiano Reggiano 36-Month (200g)', brand: 'Cravero',
    category: 'Artisan Cheeses', subcategory: 'Hard Cheeses',
    country: 'Italy', flag: '🇮🇹',
    price: 2200, mrp: 2600, discount: 15, rating: 4.9, reviewCount: 61,
    image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400&h=300&fit=crop&auto=format',
    description: '36-month aged Parmigiano Reggiano selected personally by Cravero affineurs. Intensely crystalline and crumbly — with a profound umami, almond, and dried-fruit complexity that 24-month versions cannot match.',
    ingredients: "Raw Cow's Milk, Salt, Rennet — DOP Certified",
    factsOrUsage: 'Break, never slice | Serve with aged balsamic and honey | Exceptional on risotto or pasta.',
    isDietVegan: false, isDietOrganic: false, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  // FINE WINES & SPIRITS
  {
    id: 'p_champagne', name: 'Dom Pérignon Vintage 2015', brand: 'Moët Hennessy',
    category: 'Fine Wines & Spirits', subcategory: 'Champagne',
    country: 'France', flag: '🇫🇷',
    price: 22000, mrp: 25000, discount: 12, rating: 5.0, reviewCount: 18,
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=300&fit=crop&auto=format',
    description: 'The iconic prestige cuvée that has defined luxury Champagne since 1668. The 2015 vintage is a masterpiece of tension and energy — chalky minerality, toasted brioche, white peach, and electric acidity.',
    ingredients: 'Chardonnay & Pinot Noir grapes, Champagne, France | 12.5% ABV | 750ml',
    factsOrUsage: 'Serve at 8–10°C | Decant 20 minutes for full expression | Pairs with caviar and oysters.',
    isDietVegan: true, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_whisky', name: 'Macallan 18 Year Sherry Oak', brand: 'The Macallan',
    category: 'Fine Wines & Spirits', subcategory: 'Single Malt Whisky',
    country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    price: 28500, mrp: 32000, discount: 10, rating: 4.9, reviewCount: 23,
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=300&fit=crop&auto=format',
    description: 'The gold standard of single malt Scotch whisky. 18 years matured exclusively in hand-picked Oloroso sherry-seasoned oak casks from Jerez, Spain. Rich dried fruit, chocolate orange, and warming ginger spice.',
    ingredients: 'Single Malt Scotch Whisky, 18 Years, Speyside | 43% ABV | 700ml',
    factsOrUsage: 'Serve neat or with a single large ice sphere | Nose before sipping | Gift box included.',
    isDietVegan: true, isDietOrganic: false, isDietKeto: false, isDietGlutenFree: true, colorHex: null,
  },
  // LUXURY BEVERAGES
  {
    id: 'p_coffee', name: 'Gesha Village Anaerobic Natural (100g)', brand: 'Gesha Village Co.',
    category: 'Luxury Beverages', subcategory: 'Specialty Coffee',
    country: 'Ethiopia', flag: '🇪🇹',
    price: 4800, mrp: 5600, discount: 14, rating: 4.9, reviewCount: 34,
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=300&fit=crop&auto=format',
    description: 'Gesha Village Chaka lot — anaerobic natural processed. An extraordinary Ethiopian heirloom Gesha that defies convention. Perfume-like jasmine and rose florals, tropical mango, bergamot, and a champagne-like effervescence on the palate.',
    ingredients: '100% Single-origin Ethiopia Gesha heirloom coffee, anaerobic natural process',
    factsOrUsage: 'Grind fresh | Brew at 92°C | Best as pourover or AeroPress | Score: 93.5 SCA.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
  {
    id: 'p_matcha', name: 'First Flush Uji Ceremonial Matcha (30g)', brand: 'Ippodo Tea',
    category: 'Luxury Beverages', subcategory: 'Ceremonial Tea',
    country: 'Japan', flag: '🇯🇵',
    price: 3200, mrp: 3800, discount: 15, rating: 4.8, reviewCount: 47,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop&auto=format',
    description: "Ippodo's finest ceremonial grade matcha, harvested from shade-grown Uji tencha in the first spring flush. Brilliant emerald green with an exceptionally smooth, almost creamy sweetness and zero bitterness.",
    ingredients: '100% Ceremonial grade Uji Matcha (Camellia sinensis), stone-milled',
    factsOrUsage: 'Sift 1.5g into warmed bowl | Add 70°C water | Whisk in W-motion with bamboo chasen.',
    isDietVegan: true, isDietOrganic: true, isDietKeto: true, isDietGlutenFree: true, colorHex: null,
  },
];

export const CATEGORIES = ['All','Groceries (Exotic)','Snacks','Ready-to-Eat',
  'Meats & Seafood','Artisan Cheeses','Fine Wines & Spirits','Luxury Beverages',
  'Makeup','Skincare','Hair Care'];

export const BASE_COUPONS = {
  'WELCOME':    { type: 'flat',    value: 250 },
  'AMEXGOLD':   { type: 'percent', value: 15  },
  'MLUXMAYANK': { type: 'flat',    value: 200 },
};

// Complementary pairings for recommendation engine
export const PRODUCT_PAIRINGS = {
  p_champagne:    ['p_truffle','p_cheese_brie','p_caviar_chips','p_iberico','p_bluefin'],
  p_whisky:       ['p_cheese_parm','p_gold_chocolate','p_iberico','p_wagyu_steak'],
  p_truffle:      ['p_champagne','p_wagyu_steak','p_mac_truffle','p_cheese_parm'],
  p_wagyu_steak:  ['p_truffle','p_champagne','p_cheese_parm','p_iberico'],
  p_wagyu_sliders:['p_caviar_chips','p_matcha_pocky','p_champagne'],
  p_cheese_brie:  ['p_champagne','p_honey','p_iberico','p_cheese_parm'],
  p_cheese_parm:  ['p_whisky','p_truffle','p_iberico','p_champagne'],
  p_mango:        ['p_matcha','p_honey','p_matcha_pocky'],
  p_coffee:       ['p_gold_chocolate','p_matcha_pocky','p_honey'],
  p_matcha:       ['p_matcha_pocky','p_honey','p_gold_chocolate'],
  p_lobster_roll: ['p_champagne','p_cheese_brie','p_langoustine'],
  p_bluefin:      ['p_champagne','p_saffron','p_mango'],
  p_langoustine:  ['p_champagne','p_cheese_brie','p_bluefin'],
  p_iberico:      ['p_champagne','p_cheese_brie','p_cheese_parm'],
  p_lipstick_gold:    ['p_lipstick_crimson','p_foundation_silk','p_serum_orchid'],
  p_lipstick_crimson: ['p_lipstick_gold','p_foundation_silk','p_eye_cream'],
  p_serum_orchid: ['p_eye_cream','p_saffron_oil','p_foundation_silk'],
  p_hair_elixir:  ['p_hair_mask','p_saffron_oil'],
  p_saffron:      ['p_honey','p_mango','p_saffron_oil'],
  p_honey:        ['p_cheese_brie','p_saffron','p_gold_chocolate'],
};
